name: Docker CI

on:
  push:
    branches:
      - master

jobs:

  docker:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare variables
        id: vars
        run: |
          DOCKER_IMAGE=dhananjay12/static-nginx
          echo ::set-output name=image::${DOCKER_IMAGE}
          echo ::set-output name=sha_short::$(git rev-parse --short HEAD)

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and tag Docker image
        run: docker build . --file Dockerfile --tag ${{steps.vars.outputs.image}}:latest

      - name: Retag the image to latest
        run: docker tag ${{steps.vars.outputs.image}}:latest ${{steps.vars.outputs.image}}:${{steps.vars.outputs.sha_short}}

      - name: Push Images
        run: |
          docker push ${{steps.vars.outputs.image}}:latest
          docker push ${{steps.vars.outputs.image}}:${{steps.vars.outputs.sha_short}}


